version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  engine-fetcher:
    build: 
      context: ./go
      dockerfile: Dockerfile
    environment:
      - APP_ROLE=fetcher
      - REDIS_URL=redis:6379
      - SYMBOLS=btcusdt,ethusdt,solusdt,bnbusdt
    depends_on:
      - redis
    restart: unless-stopped

  engine-processor:
    build:
      context: ./go
      dockerfile: Dockerfile
    environment:
      - APP_ROLE=processor
      - REDIS_URL=redis:6379
      - SYMBOLS=btcusdt,ethusdt,solusdt,bnbusdt
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: unless-stopped
