---
# --- Fetcher Service ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine-fetcher
  template:
    metadata:
      labels:
        app: engine-fetcher
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: fetcher
        image: ghcr.io/jaycchiu524/crypto-monitoring-engine-go:latest
        imagePullPolicy: Always
        env:
        - name: APP_ROLE
          value: "fetcher"
        - name: SYMBOLS
          valueFrom:
            configMapKeyRef:
              name: crypto-config
              key: SYMBOLS
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: crypto-config
              key: REDIS_URL
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_PASSWORD
---
# --- Processor Service ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine-processor
  template:
    metadata:
      labels:
        app: engine-processor
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: processor
        image: ghcr.io/jaycchiu524/crypto-monitoring-engine-go:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: metrics
        env:
        - name: APP_ROLE
          value: "processor"
        - name: SYMBOLS
          valueFrom:
            configMapKeyRef:
              name: crypto-config
              key: SYMBOLS
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: crypto-config
              key: REDIS_URL
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_PASSWORD
---
# --- Metrics Service ---
apiVersion: v1
kind: Service
metadata:
  name: engine-metrics
spec:
  type: NodePort
  selector:
    app: engine-processor
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
