---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-observability
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 2.10.2
    chart: loki-stack
    helm:
      values: |
        loki:
          isDefault: true
        promtail:
          enabled: true
          config:
            positions:
              filename: /tmp/positions.yaml
          podSecurityContext:
            runAsUser: 0
            runAsGroup: 0
            seLinuxOptions:
              type: spc_t

        grafana:
          enabled: true
          service:
            type: NodePort
            nodePort: 30082
          sidecar:
            datasources:
              enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
